gamefolio/urls.py
from django.contrib import admin
from django.urls import include, path, reverse
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

from gamefolio_app import views

handler404 = 'gamefolio_app.views.handler404'
urlpatterns = [
    path('', views.IndexView.as_view(), name ="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('gamefolio/', include('gamefolio_app.urls', namespace='gamefolio')),
]+ static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gamefolio_app/urls.py
from django.urls import path
from gamefolio_app import views

app_name = 'gamefolio_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    
    path('accounts/register/', views.MyRegistrationView.as_view(), name='registration_register'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),  
    
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    
    path('lists/', views.ListsView.as_view(), name='lists'),
    path('create_list/', views.CreateListView.as_view(), name='create_list'),
    path('get-game/', views.AddListGame.as_view(), name='get_game'),
    path('<str:author_username>/<slug:slug>/delete/', views.ListDeleteView.as_view(), name='list_delete'),
    path('list/<author_username>/<slug:slug>', views.ListView.as_view(), name='list'),
    path('list/<author_username>/<slug:slug>/edit/', views.EditListView.as_view(), name='list_edit'),
    
    path('suggest/', views.InlineSuggestionsView.as_view(), name='suggest'),
    path('search/', views.SearchView.as_view(), name='search'),
    
    path('game/<slug:game_id>/', views.GamePageView.as_view(), name="game"),
    path('like_review/', views.LikeReviewView.as_view(), name='like_review'),

    path('add_to_list_form/<slug:slug>/<slug:game_id>/', views.AddToListFormView.as_view(), name='add_to_list_form'),
]

gamefolio_app/models.py
from django.db import models
from django.db.models import Avg
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils import timezone

class Author(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    website = models.URLField(blank = True)
    picture = models.ImageField(upload_to="profile_images", default="defaultprofile.png")
    bio = models.TextField(default = "This user has no bio.")

    def __str__(self):
        return f"{self.user.username}"

class Game(models.Model):
    id = models.SlugField(unique = True, primary_key = True)

    title = models.CharField(max_length = 128, blank = False, db_index = True)
    genre = models.CharField(max_length = 128)                                   
    pictureId = models.CharField(max_length = 32)                               
    description = models.TextField(default = "This game has no description.")   
    views = models.IntegerField(default = 0)

    def average_rating(self):
        average = Review.objects.filter(game=self.id).aggregate(Avg('rating'))['rating__avg']
        average = average * 5 if average != None else 0
        return int(average)/10
    
    def average_text_rating(self):
        average = self.average_rating()
        average = int(average*2+0.25)
        return Review.RATING_CHOICES[average][1]
    
    def total_reviews(self):
        return Review.objects.filter(game=self.id).count()
    
    #ImageTypes         Size
    #micro              35 x 35
    #thumb              90 x 90
    #cover_small        90 x 128
    #cover_big          264 x 374
    #screenshot_huge    1280 x 720
    #720p               720 x 1280
    #1080p              1080 x 1920
    def get_image(self, image_type):
        return f"https://images.igdb.com/igdb/image/upload/t_{image_type}/{self.pictureId}.jpg"

    def __str__(self):
        return self.title

class Review(models.Model):
    RATING_CHOICES = (
        (0, "No Ratings"),
        (1, "½"), 
        (2, "★"),
        (3, "★½"),
        (4, "★★"),
        (5, "★★½"),
        (6, "★★★"),
        (7, "★★★½"),
        (8, "★★★★"),
        (9, "★★★★½"),
        (10, "★★★★★"),
    )

    game = models.ForeignKey(Game, on_delete = models.CASCADE, db_index = True, db_column='game')
    author = models.ForeignKey(Author, on_delete = models.CASCADE)
   
    content = models.TextField(blank = False)
    views = models.IntegerField(default = 0)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)  #Only allows 1-10 ratings or 1/2-5 stars
    datePosted = models.DateTimeField(default=timezone.now())
    likes = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if int(self.rating) < 1 or int(self.rating) > 10:
            self.rating = max(min(self.rating, 10), 1) #Clamps rating between 1 and 10
        super(Review, self).save(*args, **kwargs)

    def __str__(self):
        return self.author.user.username + " - " + self.game.title + ": " + self.RATING_CHOICES[self.rating-1][1]
          

class List(models.Model):
    author = models.ForeignKey(Author, on_delete = models.CASCADE)

    slug = models.SlugField()  #NOT UNIQUE as two users can have list with same name
    title = models.CharField(max_length = 128, blank = False)
    description = models.TextField(default = "", blank = True)
    views = models.IntegerField(default = 0)

    def save(self, *args, **kwargs):
        #Same idea as gameslug, if user has list with two same names, create indexed slug
        if(self.slug == ""):
            slug = slugify(self.title)                                      
            index = List.objects.filter(author=self.author, slug__startswith=slug).count()    
            if(index != 0):                   
                while(List.objects.filter(author=self.author, slug=slug+"-"+str(index)).count() > 0):
                    index += 1;                          
                slug += "-" + str(index)                                
            self.slug = slug         
        super(List, self).save(*args, **kwargs)

    def __str__(self):
        return self.author.user.username + " - " + self.title
    
class ListEntry(models.Model):
    list = models.ForeignKey(List, on_delete = models.CASCADE)
    game = models.ForeignKey(Game, on_delete = models.CASCADE)

    class Meta:
        verbose_name_plural = "List Entries"

    def __str__(self):
        return str(self.list) + " : " + str(self.game)
    

gamefolio_app/views.py
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.db.models import Avg, Count, Sum
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from registration.backends.simple.views import RegistrationView
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from gamefolio_app.forms import ReviewForm, UserForm , AuthorForm, CreateListForm
from gamefolio_app.models import Game, Review, Author, List, ListEntry
from django.core.paginator import Paginator
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render_to_response
from django.http import Http404  

class IndexView(View):
    def get(self, request):
        game_list = Game.objects.annotate(average_ratings=Avg('review__rating')).order_by('-average_ratings')[:4]
        reviews_list = Review.objects.order_by('-likes')[:6]
        visitor_cookie_handler(request)
        
        context_dict = {}
        context_dict['games'] = game_list
        context_dict['reviews'] = reviews_list
        context_dict['visits'] = request.session['visits']
        
        return render(request, 'gamefolio_app/index.html', context=context_dict)
      
class MyRegistrationView(RegistrationView):
    def form_invalid(self, form):
        response = super().form_invalid(form)
        for field, errors in form.errors.items():
            field_name = form.fields[field].label
            for error in errors:
                messages.error(self.request, f"{field_name}: {error}")
        return response

    def get_success_url(self, user=None):
        return reverse('gamefolio_app:register_profile')
    

@method_decorator(login_required, name='dispatch')
class RegisterProfileView(View):

    def get(self, request):
        form = AuthorForm()
        context = {'form': form}
        return render(request, 'gamefolio_app/profile_registration.html', context)

    def post(self, request):
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect(reverse('gamefolio_app:index'))
        else:
            print(form.errors)

        context = {'form': form}
        return render(request, 'gamefolio_app/profile_registration.html', context)
    

class UserLoginView(View):
    template_name = 'gamefolio_app/registration/login.html'  

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('gamefolio_app:profile'))
            else:
                return HttpResponse("Your Gamefolio account is disabled")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")


@method_decorator(login_required, name='dispatch')
class UserLogoutView(LogoutView):
    next_page = reverse_lazy('gamefolio_app:auth_logout')
    
class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
            lists = List.objects.filter(author=user.author)
        except User.DoesNotExist:
            return None
        user_profile = Author.objects.get_or_create(user=user)[0]
        form = AuthorForm({'website': user_profile.website, 'picture': user_profile.picture, 'bio': user_profile.bio})

        return (user, lists, user_profile, form)
    
    def get(self, request, username):
        try:
            (user, lists, user_profile, form) = self.get_user_details(username)
            user_reviews = Review.objects.filter(author=user_profile)
            user_reviews = user_reviews.annotate(likes_total=Sum('likes'))
            user_reviews_count = len(user_reviews)
        except TypeError:
            return redirect(reverse('gamefolio_app:index'))
        
        sort_reviews_by = request.GET.get('sort_reviews', 'recent')
        
        if sort_reviews_by == 'liked':
            user_reviews = user_reviews.annotate(likes_total=Sum('likes')).order_by('-likes_total', '-datePosted')
        elif sort_reviews_by == 'recent':
            user_reviews = user_reviews.order_by('-datePosted')
        elif sort_reviews_by == 'rating':
            user_reviews = user_reviews.order_by('-rating')

        context_dict = {'user_profile': user_profile, 'count':user_reviews_count, 'selected_user': user, 'user_lists':lists,'form': form, 'user_reviews': user_reviews, 'sort_reviews_by': sort_reviews_by}
        return render(request, 'gamefolio_app/profile.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, lists, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('gamefolio_app:index'))
        
        if request.user != user:
            return HttpResponse("Unauthorized access")
            
        form = AuthorForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('gamefolio_app:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile, 'selected_user': user, 'form': form}
        return render(request, 'gamefolio_app/profile.html', context_dict)

class ListProfilesView(View):
    def get(self, request):
        MAX_RESULTS_PER_PAGE = 12
        profiles = Author.objects.annotate(total_reviews=Count('review'), total_likes=Sum('review__likes'))
        profiles_count = len(profiles)
        sort_by = request.GET.get('sort', default='likes')
        
        if sort_by == 'reviews':
            profiles = profiles.order_by('-total_reviews')
        elif sort_by == "likes":
            profiles = profiles.order_by('-total_likes')
        elif sort_by == "alphabetical":
            profiles = profiles.order_by('user__username')
                     
        try:
            page = request.GET['page'].strip()
        except Exception as e:
            page = 0
            
        page_count = profiles_count/MAX_RESULTS_PER_PAGE
        
        if(page_count == int(page_count)):
            page_count = int(page_count)
        else:
            page_count = int(page_count) + 1
        page_count = max(page_count,1)  
        
        try:
            page = int(page)
            assert(page >= 0)
            assert(page < page_count)
        except Exception as e:
            print(e)
            raise Http404  
        
        offset = page * MAX_RESULTS_PER_PAGE
        actual_results = profiles[offset:MAX_RESULTS_PER_PAGE+offset]
        current_page = page + 1
        
        pages = calculate_pages(page_count, current_page)
        
        context_dict = {"authors" : actual_results, "count": profiles_count, "pages": pages, "current_page": current_page, "page_count": page_count, "sort_by": sort_by}
        return render(request, 'gamefolio_app/list_profiles.html', context_dict)
      
class ListView(View):
    def get(self, request, author_username, slug):
        list_obj = get_object_or_404(List, author__user__username=author_username, slug=slug)
        list_obj.views += 1
        list_obj.save()      
        list_entries = list_obj.listentry_set.all()
        all_games = Game.objects.all().order_by('title')
        context = {'list_obj': list_obj, 'list_entries': list_entries, 'all_games': all_games, 'views': request.session['visits']}
        return render(request, 'gamefolio_app/list.html', context)
    
    @method_decorator(login_required)
    def post(self, request, author_username, slug):
        list_obj = get_object_or_404(List, author__user__username=author_username, slug=slug)
        if request.user == list_obj.author.user:
            game_id = request.POST.get('game')
            game = get_object_or_404(Game, id=game_id)
            ListEntry.objects.create(list=list_obj, game=game)
        return redirect('gamefolio_app:list', author_username=author_username, slug=slug)

class EditListView(View):
    @method_decorator(login_required)
    def get(self, request, author_username, slug):
        list_obj = get_object_or_404(List, author__user__username=author_username, slug=slug)
        create_list_form = CreateListForm({"title": list_obj.title, "description": list_obj.description})
        list = ListEntry.objects.all()
        context_dict = {
                        'user_list' : list,
                        'form': create_list_form,
                        "title": list_obj.title,
                        "entries": ListEntry.objects.filter(list = list_obj)}
        
        return render(request, 'gamefolio_app/create_list.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, author_username, slug): 
        create_list_form = CreateListForm(request.POST)
        create_list_form.is_valid()
        if "title" in create_list_form.data.keys():
            list_obj = get_object_or_404(List, author__user__username=author_username, slug=slug)
            list_obj.description = create_list_form.data["description"]

templates/gamefolio_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load tags %}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Favicon-->
    <link href="{% static 'images/favicon.ico' %}" rel="icon" >

    <title>
        Gamefolio - {% block title_block %} {% endblock %}
    </title>
    
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<!-- Navigation-->

<body class="d-flex flex-column h-100 flex-wrapper">
    <main class="flex-shrink-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
                <div class="container px-5">
                    <h4><a class="navbar-brand" href="{% url 'gamefolio_app:index' %}">GameFolio</a></h4>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <!-- Search bar -->
                            <li class="nav-item">
                                <form class="d-flex" action="{% url 'gamefolio_app:search' %}" method = "get" id ="search-form">
                                    <button type="submit" class = "d-none"></button>
                                    <input type="hidden" name="query" value="" id="search-query-parameter"/> 
                                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id = "search-bar" value = "{{ query }}">
                                    <button class="btn bg-transparent border-none" style="margin-left: -40px; z-index: 100;" type="hidden" id = "reset-button"><div class = "fw-light d-flex align-items-center text-center">&times;</div></button>
                                    <button class="btn btn-outline-success" type="submit" id = "search-button">Search</button>
                                </form>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'gamefolio_app:index' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'gamefolio_app:list_profiles' %}">Users</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'gamefolio_app:lists' %}">Lists</a></li>
                            <img class="card-img-top" src="{{ MEDIA_URL }}{{ user.author.picture }}" alt="Profile Picture" style="width: 40px; height: 40px; border-radius: 5px; margin-left: 20px;">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {% if user.is_authenticated %}
                                    Profile
                                    {% else %}
                                    Login/Register
                                    {% endif %}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown" id="profileDropdown">
                                    {% if user.is_authenticated %}
                                    <li><a class="dropdown-item" href="{% url 'gamefolio_app:profile' user.username %}">My Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'auth_password_change' %}">Change Password</a></li>
                                    <li><a class="dropdown-item" href="{% url 'auth_logout' %}">Logout</a></li>
                                    {% else %}
                                    <li><a class="dropdown-item" href="{% url 'auth_login' %}">Login</a></li>
                                    <li><a class="dropdown-item" href="{% url 'gamefolio_app:registration_register' %}">Register</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            
            {% block body_block %}
            <!-- Main Body -->
            {% endblock %}
    </main>
    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; GameFolio 2024</div></div>
                <div class="col-auto">
                    <a id="privacy-button" class="link-light small" href="#!">Privacy</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a id="terms-button" class="link-light small" href="#!">Terms</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a id="contact-button" class="link-light small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>


    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- JQuery-->
    <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script
    src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"
    integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://unpkg.com/feather-icons@4.10.0/dist/feather.min.js"></script>
    <script>
        feather.replace()
    </script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- AJAX script -->
    <script src="{% static 'js/gamefolio-ajax.js' %}"></script>
    <!-- Search script -->
    <script src="{% static 'js/search-functionality-scripts.js' %}"></script>

    
    {% block footer %}
    {% endblock %}

</body>
</html>

templates/gamefolio_app/game_card.html
{% load tags %}
{% load static %}
<div class="col-lg-3 col-sm-4 col-6 mb-5">
    <div class="card h-100 shadow border-0"> 
        <a  href="{% url 'gamefolio_app:game' game.id %}"><img class="card-img{%if verbose%}-top{%endif%} game-review-image" src="{% get_image game "720p" %}" alt="{{ game.title }} thumbnail" /></a>
        {% if verbose %}
        <div class="card-body p-4">
            <a href = "{% url 'gamefolio_app:search' %}?genre={{game.genre}}"><button type="genre" class="btn btn-outline-success">{{ game.genre }}</button></a>
            <h5 class="card-title mb-3"></h5>
            <div style="color: #198754">{{ game.average_text_rating }}</div> 
            <h3 class="card-title mb-3"><a  href="{% url 'gamefolio_app:game' game.id %}" class="game-review-link"><strong>{{ game.title }}</strong></a></h3>
            <p class="card-text mb-0">{{ game.description|truncatechars:100 }}</p>
        </div>
        {% endif %}
    </div>
</div>

templates/gamefolio_app/list.html
{% extends 'gamefolio_app/base.html' %}
{% load static %}
{% load tags %}

{% block title_block %}
    {{ list_obj.title }} - Games List
{% endblock %}

{% block body_block %}
<header class="bg-dark pt-4 d-flex justify-content-center"> 
    <div class="container px-5 mx-5">
        <div class="row gx-5 align-items-center d-flex justify-content-center">
            <div class="col-md-8 col-12">
                <div class="my-4 text-center text-xl-start">
                    <div class = "row d-flex align-items-end">
                        <div class = "col">
                            <div class ="row d-inline">
                                <h1 class="display-5 d-inline fw-bolder text-white mb-2 pe-0">{{ list_obj.title }}</h1>
                                
                                <p class="lead fw-bold text-white-25 mb-4 d-inline px-0 ms-2">{{ list_obj.views }} views</p>
                            </div>
                        </div>
                        <div class ="col d-flex justify-content-start mx-4">
                            <div class ="row d-flex align-items-end">
                                <a class = "mx-3 px-0" href = "{% url 'gamefolio_app:profile' list_obj.author.user.username %}"  style = "width: fit-content;"><img class="shadow-sm rounded-circle px-0 mx-0 user-review-image" src="{{MEDIA_URL}}{{ list_obj.author.picture }}" alt="{{ list_obj.author.user}} profile picture" /></a>
                                <p class="lead fw-normal text-white mx-0 px-0 mb-0 align-text-bottom" style = " width: fit-content;">
                                    <a class="list-profile-link mb-0" href="{% url 'gamefolio_app:profile' list_obj.author.user.username %}" >{{ list_obj.author.user.username }}</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% if list_obj.description %}
                    <label class="lead fw-bold text-white-50 mb-0 mt-4 py-0" for="description">Description</label>
                    <p class="lead fw-normal text-white mb-4" style = "overflow-wrap: break-word;" name = "description">{{ list_obj.description }}</p>
                    {% endif %}
                    
                    {% if user.is_authenticated and user == list_obj.author.user %}
                    <div class = "row d-flex mt-4">
                        <form class = "col-3" method="get" action="{% url 'gamefolio_app:list_edit' author_username=list_obj.author.user.username slug=list_obj.slug %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary">Edit List</button>
                        </form>
                        <form class = "col-3" method="post" action="{% url 'gamefolio_app:list_delete' author_username=list_obj.author.user.username slug=list_obj.slug %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete List</button>
                        </form>
                    </div>
                    {% endif %}
                    
                </div>
            </div>
            <div class="col-md-4 d-md-block d-none text-center">
                <div class = "row d-flex justify-content-end">
                {% render_list_images list_obj %}
                </div>
            </div>
        </div>
    </div>
</header>

<section class="py-5">
    <div class="container px-5 my-2">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Games</h2>
                </div>
            </div>
        </div>
        <hr class ="mb-4">
        <div class="row gx-5">
            {% for entry in list_entries %}
                {% render_game_card entry.game verbose=False%}
            {% endfor %}
        </div> 
    </div>
</section>


{% endblock %}

templates/gamefolio_app/list_entry.html
{% load tags %}
{% load static %}
<div id = "list-entry" class="mb-5" style = "width: 20% !important; max-width: 20% important!;">
    <div class="card h-100 shadow border-0"> 
        <img class="card-img list-entry-image" src="{% get_image game "720p" %}" alt="{{ game.title }} thumbnail" />
        <button class ="btn-dark px-2 py-1 list-entry-remove-btn d-none"  tabindex="-1" style="position: absolute!important; bottom:4%!important; left: 50%!important; transform: translateX(-50%)!important">X</button>
    </div>
    <input type="hidden" value = "{{game.id}}" name = "games" id = "{{game.id}}">
</div>

templates/gamefolio_app/review.html
{% load static %}
{% load tags %}

<div class = "{% if paginate %}user-review{%endif%} col-md-12 col-lg-6 col-xl-4 my-3 py-3">
    <div class = "row d-flex align-items-end">
        {% if verbose %}
        <div class = "col-md-4">
            <a href="{% url 'gamefolio_app:game' review.game.id %}">
                <img class = "border border-2 border-light shadow-sm img-fluid rounded game-review-image" src={% get_image review.game "cover_big" %} alt="{{ review.game.title }} thumbnail"  />
            </a>
        </div>
        {% endif %}
        <div class = "col-8">
            <div class = "row-2 d-flex align-items-left mt-3">
                <div class = "col-2">
                    <a href = "{% url 'gamefolio_app:profile' review.author.user.username %}">
                        <img class="shadow-sm rounded-circle me-3 user-review-image" src="{% get_media_prefix %}{{ review.author.picture }}" alt="{{ review.author.user}} profile picture" />
                    </a>
                </div>
                    <div class="col px-2 d-flex align-items-end">
                        <a class = "user-review-link text-decoration-none link-dark " href = "{% url 'gamefolio_app:profile' review.author.user.username %}"><h6 class = "fw-semibold"><small>{{ review.author.user}}</small></h6></a>
                    </div>
                </div>
            <div class = "row-2 mt-2">    
                {% if verbose %}
                <h4 class="mb-1 fw-semibold text-truncate"><a class="game-review-link " href="{% url 'gamefolio_app:game' review.game.id %}">{{ review.game.title }}</a></h4>
                {% endif %}
                <div style = "color: #198754">{{review.get_rating_display}}</div>
            </div>
        </div>
    </div>
    <div class = "row mt-3">
        <div>{{review.content|truncatechars:100}}</div>
    </div>
    <div class="small row mt-4 align-items-end d-flex">
        <div class ="col-6 text-muted"> {{ review.datePosted|date:"j M Y" }}  </div>
        <div class ="like-count col-4 text-muted text-end"> {{ review.likes }} likes </div>
        {% if user.is_authenticated and user != review.author.user%}
        <button 
                data-reviewid="{{ review.pk }}"
                class="col-2 like-btn btn btn-outline-success btn-sm"
                type="button"
                style= "aspect: 1!important; width: 40px!important; min-wdith: 0px!important;">
            <span data-feather="thumbs-up"></span>
        </button>
        {% endif %}
    </div>
    <hr>
</div>